{application,mori,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{mori_app,[]}},
              {env,[]},
              {modules,[bops,mori_app,mori_client,mori_server,mori_sup,
                        slot]}]}.
