{application,skel,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{skel_app,[]}},
              {env,[]},
              {modules,[http_handler,skel_app,skel_engine,skel_sup,
                        ws_handler]}]}.
